### ISSUE TITLE
Violation of C++ standard in the point_cloud lib (Concurrency.h)

### ISSUE THREAD

**Issue by ShkalikovOleh** [sgumhold/cgv#32]
Dear authors,

Trying to compile some VR related stuff on GCC 11.2 (GNU/Linux Ubuntu 22.04) which use the CGV framework (_**develop**_ branch) I have found a critical error in the `Concurrency.h` header file: there are at least 2 violation of C++ standard.

1. line 84: well known incorrect behavior of the Microsoft compiler: it accepts ill-formed code. Extra qualification is not allowed, e.g instead of `inline PoolTask::PoolTask(...` it should be just `inline PoolTask(...` or even `PoolTask(...`
2. line 24: `std::condition_variable` requires including `<condition_variable>` header file.

So, can I make a PR which will fix that?

**Comment by brussig-tud** [comment]
Sure, please go ahead and submit a PR!

**Comment by brussig-tud** [comment]
Merged.
